export const RES202_FIELD_ORDER = [
  "tipo_registro",
  "consecutivo_registro",
  "codigo_habilitacion_ips_primaria",
  "tipo_identificacion_usuario",
  "numero_identificacion",
  "primer_apellido_usuario",
  "segundo_apellido_usuario",
  "primer_nombre_usuario",
  "segundo_nombre_usuario",
  "fecha_nacimiento",
  "sexo",
  "codigo_pertenencia_etnica",
  "codigo_ocupacion",
  "codigo_nivel_educativo",
  "gestacion",
  "sifilis_gestacional_o_congenita",
  "resultado_mini_mental_state",
  "hipotiroidismo_congenito",
  "sintomatico_respiratorio",
  "consumo_tabaco",
  "lepra",
  "obesidad_o_desnutricion_proteico_calorica",
  "resultado_tacto_rectal",
  "acido_folico_preconcepcional",
  "resultado_prueba_sangre_oculta_materia_fecal",
  "enfermedad_mental",
  "cancer_cervix",
  "agudeza_visual_lejana_oi",
  "agudeza_visual_lejana_od",
  "fecha_peso",
  "peso_kg",
  "fecha_talla",
  "talla_cm",
  "fecha_probable_parto",
  "codigo_pais",
  "clasificacion_riesgo_gestacional",
  "resultado_colonoscopia_tamizaje",
  "resultado_tamizaje_auditivo_neonatal",
  "resultado_tamizaje_visual_neonatal",
  "dpt_menores_5",
  "resultado_tamizaje_vale",
  "neumococo",
  "resultado_tamizaje_hepatitis_c",
  "resultado_ead_motricidad_gruesa",
  "resultado_ead_motricidad_finoadaptativa",
  "resultado_ead_personal_social",
  "resultado_ead_audicion_lenguaje",
  "tratamiento_ablativo_escision_post_iva",
  "resultado_oximetria_pre_post_ductal",
  "fecha_atencion_parto_cesarea",
  "fecha_salida_parto_cesarea",
  "fecha_atencion_promocion_apoyo_lactancia",
  "fecha_consulta_valoracion_integral",
  "fecha_atencion_asesoria_anticoncepcion",
  "suministro_metodo_anticonceptivo",
  "fecha_suministro_metodo_anticonceptivo",
  "fecha_primera_consulta_prenatal",
  "resultado_glicemia_basal",
  "fecha_ultimo_control_prenatal",
  "suministro_acido_folico_prenatal",
  "suministro_sulfato_ferroso_prenatal",
  "suministro_carbonato_calcio_prenatal",
  "fecha_valoracion_agudeza_visual",
  "fecha_tamizaje_vale",
  "fecha_tacto_rectal",
  "fecha_oximetria_pre_post_ductal",
  "fecha_colonoscopia_tamizaje",
  "fecha_prueba_sangre_oculta_materia_fecal",
  "consulta_psicologia",
  "fecha_tamizaje_auditivo_neonatal",
  "suministro_fortificacion_casera_6a23m",
  "suministro_vitamina_a_24a60m",
  "fecha_toma_ldl",
  "fecha_toma_psa",
  "preservativos_entregados_its",
  "fecha_tamizaje_visual_neonatal",
  "fecha_atencion_salud_bucal_odontologia",
  "suministro_hierro_24a59m",
  "fecha_antigeno_superficie_hb",
  "resultado_antigeno_superficie_hb",
  "fecha_toma_tamizaje_sifilis",
  "resultado_tamizaje_sifilis",
  "fecha_toma_prueba_vih",
  "resultado_prueba_vih",
  "fecha_tsh_neonatal",
  "resultado_tsh_neonatal",
  "tamizaje_cancer_cuello_uterino",
  "fecha_tamizaje_cancer_cuello_uterino",
  "resultado_tamizaje_cancer_cuello_uterino",
  "calidad_muestra_citologia_cervicouterina",
  "codigo_habilitacion_ips_tamizaje_cancer_cuello_uterino",
  "fecha_colposcopia",
  "resultado_ldl",
  "fecha_biopsia_cervicouterina",
  "resultado_biopsia_cervicouterina",
  "resultado_hdl",
  "fecha_mamografia",
  "resultado_mamografia",
  "resultado_trigliceridos",
  "fecha_toma_biopsia_mama",
  "fecha_resultado_biopsia_mama",
  "resultado_biopsia_mama",
  "cop_por_persona",
  "fecha_toma_hemoglobina",
  "resultado_hemoglobina",
  "fecha_toma_glicemia_basal",
  "fecha_toma_creatinina",
  "resultado_creatinina",
  "fecha_hemoglobina_glicosilada",
  "resultado_psa",
  "fecha_toma_tamizaje_hepatitis_c",
  "fecha_toma_hdl",
  "fecha_toma_baciloscopia_dx",
  "resultado_baciloscopia_dx",
  "clasificacion_riesgo_cardiovascular",
  "tratamiento_sifilis_gestacional",
  "tratamiento_sifilis_congenita",
  "clasificacion_riesgo_metabolico",
  "fecha_toma_trigliceridos",
] as const;

export type Res202Key = typeof RES202_FIELD_ORDER[number];
export type Res202Row = Record<Res202Key, any>;

/** Etiquetas visibles (los nombres tal cual nos pasaste) */
export const RES202_LABELS: Partial<Record<Res202Key, string>> = {
  tipo_registro: "Tipo de registro",
  consecutivo_registro: "Consecutivo de registro",
  codigo_habilitacion_ips_primaria: "Código de habilitación IPS primaria",
  tipo_identificacion_usuario: "Tipo de identificación del usuario",
  numero_identificacion: "Numero de Identificacion",
  primer_apellido_usuario: "Primer apellido del usuario",
  segundo_apellido_usuario: "Segundo apellido del usuario",
  primer_nombre_usuario: "Primer nombre del usuario",
  segundo_nombre_usuario: "Segundo nombre del usuario",
  fecha_nacimiento: "Fecha de Nacimiento",
  sexo: "Sexo",
  codigo_pertenencia_etnica: "Código pertenencia étnica",
  codigo_ocupacion: "Código de ocupación",
  codigo_nivel_educativo: "Código de nivel educativo",
  gestacion: "Gestación",
  sifilis_gestacional_o_congenita: "Sífilis Gestacional o congénita",
  resultado_mini_mental_state: "Resultado de la prueba  mini - mental state",
  hipotiroidismo_congenito: "Hipotiroidismo Congénito",
  sintomatico_respiratorio: "Sintomático Respiratorio",
  consumo_tabaco: "Consumo de tabaco",
  lepra: "Lepra",
  obesidad_o_desnutricion_proteico_calorica: "Obesidad o Desnutrición Proteico Calórica",
  resultado_tacto_rectal: "Resultado del tacto rectal",
  acido_folico_preconcepcional: "Acido fólico preconcepcional",
  resultado_prueba_sangre_oculta_materia_fecal: "Resultado de la prueba de sangre oculta en materia fecal",
  enfermedad_mental: "Enfermedad Mental",
  cancer_cervix: "Cáncer de Cérvix",
  agudeza_visual_lejana_oi: "Agudeza visual lejana ojo izquierdo",
  agudeza_visual_lejana_od: "Agudeza visual lejana ojo derecho",
  fecha_peso: "Fecha del Peso",
  peso_kg: "Peso en Kilogramos",
  fecha_talla: "Fecha de la Talla",
  talla_cm: "Talla en Centímetros",
  fecha_probable_parto: "Fecha Probable de Parto",
  codigo_pais: "Código país",
  clasificacion_riesgo_gestacional: "Clasificación del riesgo gestacional",
  resultado_colonoscopia_tamizaje: "Resultado de colonoscopia tamizaje",
  resultado_tamizaje_auditivo_neonatal: "Resultado de tamizaje auditivo neonatal",
  resultado_tamizaje_visual_neonatal: "Resultado de tamizaje visual neonatal",
  dpt_menores_5: "DPT menores de 5 años",
  resultado_tamizaje_vale: "Resultado de tamizaje VALE",
  neumococo: "Neumococo",
  resultado_tamizaje_hepatitis_c: "Resultado de tamizaje para hepatitis C",
  resultado_ead_motricidad_gruesa: "Resultado de escala abreviada de desarrollo área de motricidad gruesa",
  resultado_ead_motricidad_finoadaptativa: "Resultado de escala abreviada de desarrollo área de motricidad finoadaptativa",
  resultado_ead_personal_social: "Resultado de escala abreviada de desarrollo área personal social",
  resultado_ead_audicion_lenguaje: "Resultado de escala abreviada de desarrollo área de motricidad audición lenguaje",
  tratamiento_ablativo_escision_post_iva: "Tratamiento ablativo o de escisión posterior a la realización de la técnica de inspección visual (Crioterapia o LETZ)",
  resultado_oximetria_pre_post_ductal: "Resultado de tamización con oximetría pre y post ductal",
  fecha_atencion_parto_cesarea: "Fecha atención parto o cesárea",
  fecha_salida_parto_cesarea: "Fecha salida de la atención del parto o cesárea",
  fecha_atencion_promocion_apoyo_lactancia: "Fecha de atención en salud para la promoción y apoyo de la lactancia materna",
  fecha_consulta_valoracion_integral: "Fecha de consulta de valoración integral",
  fecha_atencion_asesoria_anticoncepcion: "Fecha de atención en salud para la asesoría en anticoncepción",
  suministro_metodo_anticonceptivo: "Suministro de Método Anticonceptivo",
  fecha_suministro_metodo_anticonceptivo: "Fecha de Suministro de Método Anticonceptivo",
  fecha_primera_consulta_prenatal: "Fecha de primera consulta prenatal",
  resultado_glicemia_basal: "Resultado de glicemia basal",
  fecha_ultimo_control_prenatal: "Fecha de último control prenatal de seguimiento",
  suministro_acido_folico_prenatal: "Suministro de ácido fólico en el control prenatal",
  suministro_sulfato_ferroso_prenatal: "Suministro de sulfato ferroso en el control prenatal",
  suministro_carbonato_calcio_prenatal: "Suministro de carbonato de calcio en el control prenatal",
  fecha_valoracion_agudeza_visual: "Fecha de valoración agudeza visual",
  fecha_tamizaje_vale: "Fecha de tamizaje VALE",
  fecha_tacto_rectal: "Fecha del tacto rectal",
  fecha_oximetria_pre_post_ductal: "Fecha de tamización con oximetría pre y post ductal",
  fecha_colonoscopia_tamizaje: "Fecha de realización colonoscopia tamizaje",
  fecha_prueba_sangre_oculta_materia_fecal: "Fecha de la prueba sangre oculta en materia fecal",
  consulta_psicologia: "Consulta de Psicología",
  fecha_tamizaje_auditivo_neonatal: "Fecha de tamizaje auditivo neonatal",
  suministro_fortificacion_casera_6a23m: "Suministro de  fortificación casera en la primera infancia (6 a 23 meses)",
  suministro_vitamina_a_24a60m: "Suministro de vitamina A en la primera infancia (24 a 60 meses)",
  fecha_toma_ldl: "Fecha de toma LDL",
  fecha_toma_psa: "Fecha de toma PSA",
  preservativos_entregados_its: "Preservativos entregados a pacientes con ITS",
  fecha_tamizaje_visual_neonatal: "Fecha de tamizaje visual neonatal",
  fecha_atencion_salud_bucal_odontologia: "Fecha de atención en salud bucal por profesional en odontología",
  suministro_hierro_24a59m: "Suministro de hierro en la primera Infancia (24 a 59 meses)",
  fecha_antigeno_superficie_hb: "Fecha de antígeno de superficie hepatitis B",
  resultado_antigeno_superficie_hb: "Resultado de antígeno de superficie hepatitis B",
  fecha_toma_tamizaje_sifilis: "Fecha de toma de prueba tamizaje para sífilis",
  resultado_tamizaje_sifilis: "Resultado de prueba tamizaje para sífilis",
  fecha_toma_prueba_vih: "Fecha de toma prueba para VIH",
  resultado_prueba_vih: "Resultado de prueba para VIH",
  fecha_tsh_neonatal: "Fecha TSH Neonatal",
  resultado_tsh_neonatal: "Resultado de TSH Neonatal",
  tamizaje_cancer_cuello_uterino: "Tamizaje del cáncer de cuello uterino",
  fecha_tamizaje_cancer_cuello_uterino: "Fecha de tamizaje cáncer de cuello uterino",
  resultado_tamizaje_cancer_cuello_uterino: "Resultado tamizaje cáncer de cuello uterino",
  calidad_muestra_citologia_cervicouterina: "Calidad en la muestra de citología cervicouterina",
  codigo_habilitacion_ips_tamizaje_cancer_cuello_uterino: "Código de habilitación IPS donde se realiza  tamizaje cáncer de cuello uterino",
  fecha_colposcopia: "Fecha de Colposcopia",
  resultado_ldl: "Resultado de LDL",
  fecha_biopsia_cervicouterina: "Fecha de biopsia cervicouterina",
  resultado_biopsia_cervicouterina: "Resultado de biopsia cervicouterina",
  resultado_hdl: "Resultado de HDL",
  fecha_mamografia: "Fecha Mamografía",
  resultado_mamografia: "Resultado Mamografía",
  resultado_trigliceridos: "Resultado de triglicéridos",
  fecha_toma_biopsia_mama: "Fecha de toma biopsia de mama",
  fecha_resultado_biopsia_mama: "Fecha de resultado biopsia de mama",
  resultado_biopsia_mama: "Resultado de biopsia de mama",
  cop_por_persona: "COP por persona",
  fecha_toma_hemoglobina: "Fecha de toma hemoglobina",
  resultado_hemoglobina: "Resultado de hemoglobina",
  fecha_toma_glicemia_basal: "Fecha de toma glicemia basal",
  fecha_toma_creatinina: "Fecha de toma creatinina",
  resultado_creatinina: "Resultado de creatinina",
  fecha_hemoglobina_glicosilada: "Fecha Hemoglobina Glicosilada",
  resultado_psa: "Resultado de PSA",
  fecha_toma_tamizaje_hepatitis_c: "Fecha de toma  de tamizaje hepatitis C",
  fecha_toma_hdl: "Fecha de toma HDL",
  fecha_toma_baciloscopia_dx: "Fecha de toma de baciloscopia diagnóstico",
  resultado_baciloscopia_dx: "Resultado de baciloscopia diagnóstico",
  clasificacion_riesgo_cardiovascular: "Clasificación del riesgo cardiovascular",
  tratamiento_sifilis_gestacional: "Tratamiento para Sífilis gestacional",
  tratamiento_sifilis_congenita: "Tratamiento para Sífilis Congénita",
  clasificacion_riesgo_metabolico: "Clasificación del riesgo metabólico",
  fecha_toma_trigliceridos: "Fecha de toma triglicéridos",
};

/** Posibles alias por ciclo (opcional, amplíalo según necesites) */
export const RES202_ALIASES_BY_CICLO: Record<number, Partial<Record<Res202Key, string[]>>> = {
  1: {
    peso_kg: ["peso", "pesoKg", "peso_kg"],
    talla_cm: ["talla", "talla_cm", "tallacms", "tallaCM"],
    agudeza_visual_lejana_od: ["Agudeza_Visual_OD", "agudezaVisualOD"],
    agudeza_visual_lejana_oi: ["Agudeza_Visual_OI", "agudezaVisualOI"],
  },
  // 2: { ... }
};

/** Toma el primer valor no nulo de una lista de claves */
function coalesce(row: Record<string, any>, keys: string[]) {
  for (const k of keys) {
    const v = row?.[k];
    if (v !== null && v !== undefined) return v;
  }
  return "";
}

/** Expande una fila parcial a una fila completa 202 (con celdas vacías si falta) */
export function expandRowToRes202(row: Record<string, any>, ciclo?: number): Res202Row {
  const aliases = (ciclo && RES202_ALIASES_BY_CICLO[ciclo]) || {};
  const out: Partial<Res202Row> = {};

  for (const key of RES202_FIELD_ORDER) {
    const direct = row?.[key];
    if (direct !== undefined && direct !== null) {
      out[key] = direct;
      continue;
    }
    const alt = aliases[key];
    out[key] = alt ? coalesce(row, alt) : "";
  }

  return out as Res202Row;
}

/** Expande muchas filas a filas completas 202 */
export function expandRowsToRes202(rows: Record<string, any>[], ciclo?: number): Res202Row[] {
  return rows.map((r) => expandRowToRes202(r, ciclo));
}
